fix for issue 28: NoSuchMethodError when undeployed and when JavaMelody 1.15.0 or 1.16.0 is used with Quartz 1.7 or 1.8
git-svn-id: http://javamelody.googlecode.com/svn/trunk@1000 80d463d6-a79d-11de-ba6e-69e41c8db662