ajout slf4j dans war du serveur de collecte pour issue 102: In the collector server, NoClassDefFoundError when IBM's JVM is used
git-svn-id: http://javamelody.googlecode.com/svn/trunk@1829 80d463d6-a79d-11de-ba6e-69e41c8db662